import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.jsx";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Error from "./components/Error.jsx";
import IngredientSummary from "./components/IngredientSummary.jsx";

const dishData = [
  // ===== MAIN COURSE =====
  {
    id: 1,
    categoryId: 1,
    mealType: "MAIN COURSE",
    type: "VEG",
    name: "Palak Paneer",
    description: "Cottage cheese cooked with spinach and mild spices.",
    dishType: "CURRY",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Paneer", "Spinach", "Onion", "Tomato", "Spices"],
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 2,
    categoryId: 1,
    mealType: "MAIN COURSE",
    type: "NON-VEG",
    name: "Butter Chicken",
    description: "Tender chicken cooked with butter, cream, and spices.",
    dishType: "CURRY",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chicken", "Butter", "Cream", "Tomato", "Spices"],
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 3,
    categoryId: 2,
    mealType: "MAIN COURSE",
    type: "VEG",
    name: "Masala Dosa",
    description:
      "South Indian rice and lentil crepe with spiced potato filling.",
    dishType: "DOSAI",
    image: null,
    forChefit: true,
    forParty: false,
    nameHi: "",
    nameBn: "",
    ingredients: ["Rice", "Urad Dal", "Potato", "Onion", "Spices"],
    category: {
      id: 2,
      name: "South Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/south_indian.png",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 4,
    categoryId: 2,
    mealType: "MAIN COURSE",
    type: "VEG",
    name: "Idli Sambar",
    description: "Steamed rice cakes with lentil soup and chutneys.",
    dishType: "BREAKFAST",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Rice", "Urad Dal", "Toor Dal", "Vegetables", "Spices"],
    category: {
      id: 2,
      name: "South Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/south_indian.png",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 6,
    categoryId: 1,
    mealType: "MAIN COURSE",
    type: "NON-VEG",
    name: "Mutton Rogan Josh",
    description: "Aromatic lamb curry from Kashmir.",
    dishType: "CURRY",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Mutton", "Yogurt", "Spices", "Onion", "Ghee"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 7,
    categoryId: 2,
    mealType: "MAIN COURSE",
    type: "VEG",
    name: "Vegetable Biryani",
    description: "Fragrant rice with vegetables and spices.",
    dishType: "RICE",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Rice", "Vegetables", "Spices", "Ghee"],
    category: {
      id: 2,
      name: "South Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 8,
    categoryId: 2,
    mealType: "MAIN COURSE",
    type: "NON-VEG",
    name: "Chicken Biryani",
    description: "Classic Hyderabadi style rice and chicken with spices.",
    dishType: "RICE",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chicken", "Rice", "Spices", "Yogurt"],
    category: {
      id: 2,
      name: "South Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 9,
    categoryId: 1,
    mealType: "MAIN COURSE",
    type: "VEG",
    name: "Dal Tadka",
    description: "Yellow lentils tempered with ghee, garlic, and spices.",
    dishType: "CURRY",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Lentils", "Ghee", "Garlic", "Spices"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 10,
    categoryId: 2,
    mealType: "MAIN COURSE",
    type: "NON-VEG",
    name: "Fish Curry",
    description: "Tangy and spicy fish curry with coconut.",
    dishType: "CURRY",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Fish", "Coconut", "Spices", "Tamarind"],
    category: {
      id: 2,
      name: "South Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },

  // ===== STARTERS =====
  {
    id: 11,
    categoryId: 3,
    mealType: "STARTER",
    type: "NON-VEG",
    name: "Chilli Chicken",
    description: "Crispy fried chicken wings tossed in spicy sauce.",
    dishType: "APPETIZER",
    image: null,
    forChefit: false,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chicken", "Chili Sauce", "Garlic", "Soy Sauce"],
    category: {
      id: 3,
      name: "Chinese",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 12,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Veg Manchurian",
    description: "Crispy fried balls of vegetables in spicy garlic sauce.",
    dishType: "APPETIZER",
    image: null,
    forChefit: false,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Cabbage", "Carrot", "Flour", "Soy Sauce"],
    category: {
      id: 3,
      name: "Chinese",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 13,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Spring Rolls",
    description: "Crispy rolls stuffed with vegetables.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Vegetables", "Flour", "Soy Sauce", "Spices"],
    category: {
      id: 3,
      name: "Chinese",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 14,
    categoryId: 3,
    mealType: "STARTER",
    type: "NON-VEG",
    name: "Chicken Lollipop",
    description: "Deep-fried chicken wings with spicy coating.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chicken", "Spices", "Flour", "Oil"],
    category: {
      id: 3,
      name: "Chinese",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 15,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Paneer Tikka",
    description: "Grilled cottage cheese cubes marinated in spices.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Paneer", "Yogurt", "Spices", "Bell Pepper"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 16,
    categoryId: 3,
    mealType: "STARTER",
    type: "NON-VEG",
    name: "Seekh Kebab",
    description: "Minced meat skewers grilled with spices.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Mutton", "Spices", "Onion", "Coriander"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 17,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Aloo Tikki",
    description: "Crispy potato patties with chutney.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Potato", "Spices", "Coriander", "Chutney"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 18,
    categoryId: 3,
    mealType: "STARTER",
    type: "NON-VEG",
    name: "Fish Fingers",
    description: "Crispy golden fried fish sticks.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Fish", "Flour", "Spices", "Oil"],
    category: {
      id: 2,
      name: "South Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 19,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Hara Bhara Kabab",
    description: "Spinach and green pea patties.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Spinach", "Peas", "Potato", "Spices"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },
  {
    id: 20,
    categoryId: 3,
    mealType: "STARTER",
    type: "VEG",
    name: "Stuffed Mushrooms",
    description: "Mushrooms filled with cheese and spices.",
    dishType: "APPETIZER",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Mushroom", "Cheese", "Spices"],
    category: {
      id: 1,
      name: "North Indian",
      image: "",
      isRecommendedForMealSuggestion: true,
    },
  },

  // ===== DESSERTS =====
  {
    id: 21,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Gulab Jamun",
    description: "Traditional sweet dumplings soaked in sugar syrup.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Milk Solids", "Sugar", "Rose Water"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 22,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Kulfi",
    description: "Frozen dessert flavored with saffron & pistachio.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Milk", "Saffron", "Pistachio", "Sugar"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 23,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Rasgulla",
    description: "Spongy cheese balls soaked in sugar syrup.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chenna", "Sugar Syrup", "Cardamom"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 24,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Rasmalai",
    description: "Cottage cheese patties soaked in sweetened milk.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chenna", "Milk", "Sugar", "Cardamom"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 25,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Ice Cream",
    description: "Vanilla, chocolate, and strawberry flavors.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Milk", "Sugar", "Flavoring"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 26,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Brownie",
    description: "Rich chocolate brownie with nuts.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Chocolate", "Flour", "Nuts", "Sugar"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 27,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Cheesecake",
    description: "Creamy cheesecake with biscuit base.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Cream Cheese", "Sugar", "Biscuit Base"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 28,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Payasam",
    description: "South Indian sweet milk pudding with vermicelli.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Milk", "Vermicelli", "Sugar", "Cardamom"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 29,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Mysore Pak",
    description: "Ghee-rich gram flour sweet from Karnataka.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Gram Flour", "Ghee", "Sugar"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 30,
    categoryId: 4,
    mealType: "DESSERT",
    type: "VEG",
    name: "Halwa",
    description: "Carrot, sooji, or wheat-based Indian halwa.",
    dishType: "SWEET",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Carrot", "Sooji", "Wheat", "Sugar"],
    category: {
      id: 4,
      name: "Desserts",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },

  // ===== SIDES =====
  {
    id: 31,
    categoryId: 5,
    mealType: "SIDES",
    type: "VEG",
    name: "Naan",
    description: "Soft tandoor baked flatbread.",
    dishType: "BREAD",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Flour", "Yogurt", "Salt"],
    category: {
      id: 5,
      name: "Sides",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 32,
    categoryId: 5,
    mealType: "SIDES",
    type: "VEG",
    name: "Roti",
    description: "Whole wheat Indian bread.",
    dishType: "BREAD",

    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Wheat Flour", "Water", "Salt"],
    category: {
      id: 5,
      name: "Sides",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 33,
    categoryId: 5,
    mealType: "SIDES",
    type: "VEG",
    name: "Paratha",
    description: "Whole wheat Indian bread.",
    dishType: "BREAD",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Wheat Flour", "Ghee", "Salt"],
    category: {
      id: 5,
      name: "Sides",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 34,
    categoryId: 5,
    mealType: "SIDES",
    type: "VEG",
    name: "Chapati",
    description: "Whole wheat Indian bread.",
    dishType: "BREAD",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Wheat Flour", "Water", "Salt"],
    category: {
      id: 5,
      name: "Sides",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
  {
    id: 35,
    categoryId: 5,
    mealType: "SIDES",
    type: "VEG",
    name: "Puri",
    description: "Whole wheat Indian bread.",
    dishType: "BREAD",
    image: null,
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    ingredients: ["Wheat Flour", "Oil", "Salt"],
    category: {
      id: 5,
      name: "Sides",
      image: "",
      isRecommendedForMealSuggestion: false,
    },
  },
];

const router = createBrowserRouter([
  {
    path: "/",
    element: <App dishData={dishData} />,
  },
  {
    path: "/:id",
    element: <IngredientSummary dishData={dishData} />,
  },
  {
    path: "*",
    element: <Error />,
  },
]);

createRoot(document.getElementById("root")).render(
  <RouterProvider router={router} />
);
